### ISSUE TITLE
痛哭流涕

### ISSUE THREAD

**Issue by hesenp** [fudan-mse/latex-action#3]
老校友发现母校总算可以用LaTeX写本科生毕业论文了，开心得痛哭流涕。

**Comment by Jeff-Tian** [comment]
感谢大神的留言。

感谢 xu-cheng 的 [latex-action](https://github.com/xu-cheng/latex-action) 和 stong-zeng 的 [fduthesis](https://github.com/stone-zeng/fduthesis)。

这个 repo 克隆了 xu-cheng 的 latex-action，加入了对 fduthesis 的测试。

**Comment by Jeff-Tian** [comment]
另外，不仅支持本科论文，也支持硕士论文。@hesenp
